### ISSUE TITLE
No subtitles found error when using video method

### ISSUE THREAD

**Issue by Asinin3** [C1fer/SushiBatchTool#1]
Thank you for the amazing tool.

I ran into an issue when using the video method on all my files. I am getting an error stating that no subtitles can be found, despite the subtitle track being properly selected as you can see here:
<img width="578" height="553" alt="Image" src="https://github.com/user-attachments/assets/c5016af7-a525-40e6-b81f-5dcf9a31a3d0" />

Log:
`Sushi's running with arguments: --src "Z:/Videos/src\filename.mkv" --dst "Z:/Videos/dst\filename.mkv" --src-audio 2 --src-script 3 --dst-audio 1
No subtitles streams found in Z:/Videos/src\filename.mkv
`
The path has a \ when it goes to the subdir, but Its not caused by that, and python seems to allow using either \ or / for path on Windows. 

If I extract all the audio and subtitles I can get this tool to work with the audio method, but its much slower for me to use. ffmpeg is in path, as is mkvmerge. I can extract the audio and subfiles, then use the audio batch method and it works fine, but the video selection isn't working.

**And while I have the same issue if I run sushi directly instead of via sushi_batch.. I never had this issue previously**
Has something in this project caused this to break not only when using sushi_batch but also when trying to use sushi directly?

**Comment by C1fer** [comment]
This issue was showing up due to an error with the sushi library itself.

It was fixed in update 0.2.0.

**Comment by Asinin3** [comment]
Im still having the issue, does it work for you?

<details><summary>Media info of src mkv (Click here)</summary>
<p>

General
Unique ID                                : 208505326860228162140204686086275956458 (0x9CDCAA4E3EECC925A3BD2EA5E6E17EEA)
Complete name                            : Z:\26.mkv
Format                                   : Matroska
Format version                           : Version 2
File size                                : 340 MiB
Duration                                 : 23 min 56 s
Overall bit rate                         : 1 983 kb/s
Encoded date                             : 2012-02-13 20:13:10 UTC
Writing application                      : mkvmerge v4.0.0 ('The Stars were mine') built on Jun  6 2010 16:18:42
Writing library                          : libebml v1.0.0 + libmatroska v1.0.0

Video
ID                                       : 1
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L3
Format settings                          : CABAC / 6 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 6 frames
Codec ID                                 : V_MPEG4/ISO/AVC
Bit rate                                 : 1 559 kb/s
Nominal bit rate                         : 1 984 kb/s
Width                                    : 720 pixels
Height                                   : 480 pixels
Display aspect ratio                     : 16:9
Original display aspect ratio            : 3:2
Frame rate mode                          : Variable
Original frame rate                      : 29.970 FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.192
Writing library                          : x264 core 116 r2074 2641b9e
Encoding settings                        : cabac=1 / ref=6 / deblock=1:1:1 / analyse=0x3:0x133 / me=umh / subme=7 / psy=1 / psy_rd=0.40:0.00 / mixed_ref=1 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=2 / deadzone=21,11 / fast_pskip=1 / chroma_qp_offset=-2 / threads=3 / sliced_threads=0 / nr=0 / decimate=1 / interlaced=0 / bluray_compat=0 / constrained_intra=0 / bframes=5 / b_pyramid=0 / b_adapt=1 / b_bias=0 / direct=3 / weightb=1 / open_gop=0 / weightp=2 / keyint=250 / keyint_min=25 / scenecut=40 / intra_refresh=0 / rc_lookahead=40 / rc=2pass / mbtree=1 / bitrate=1984 / ratetol=1.0 / qcomp=0.60 / qpmin=10 / qpmax=51 / qpstep=4 / cplxblur=20.0 / qblur=0.5 / ip_ratio=1.40 / aq=1:0.60
Default                                  : Yes
Forced                                   : No

Audio #1
ID                                       : 2
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 23 min 56 s
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 6 ms
Stream size                              : 32.9 MiB (10%)
Language                                 : English
Service kind                             : Complete Main
Default                                  : Yes
Forced                                   : No

Audio #2
ID                                       : 3
Format                                   : AC-3
Format/Info                              : Audio Coding 3
Commercial name                          : Dolby Digital
Codec ID                                 : A_AC3
Duration                                 : 23 min 56 s
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 31.250 FPS (1536 SPF)
Compression mode                         : Lossy
Delay relative to video                  : 6 ms
Stream size                              : 32.9 MiB (10%)
Language                                 : Japanese
Service kind                             : Complete Main
Default                                  : No
Forced                                   : No

Text #1
ID                                       : 4
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Language                                 : English
Default                                  : Yes
Forced                                   : No

Text #2
ID                                       : 5
Format                                   : UTF-8
Codec ID                                 : S_TEXT/UTF8
Codec ID/Info                            : UTF-8 Plain Text
Language                                 : Japanese
Default                                  : No
Forced                                   : No

Text #3
ID                                       : 6
Format                                   : VobSub
Muxing mode                              : zlib
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : Picture based subtitle format used on DVDs
Language                                 : English
Default                                  : No
Forced                                   : No

Text #4
ID                                       : 7
Format                                   : VobSub
Muxing mode                              : zlib
Codec ID                                 : S_VOBSUB
Codec ID/Info                            : Picture based subtitle format used on DVDs
Language                                 : Japanese
Default                                  : No
Forced                                   : No

Menu
00:00:00.000                             : en:Chapter 16
00:01:30.833                             : en:Chapter 17
00:09:33.433                             : en:Chapter 18
00:20:31.933                             : en:Chapter 19



</p>
</details>

<details><summary>Media info of src avi (Click here)</summary>
<p>

General
Complete name                            : Z:\26.avi
Format                                   : AVI
Format/Info                              : Audio Video Interleave
Format settings                          : BitmapInfoHeader / WaveFormatEx
File size                                : 470 MiB
Duration                                 : 24 min 29 s
Overall bit rate                         : 2 680 kb/s
Frame rate                               : 23.976 FPS
Original source form/Distributed by      : ’nãƒfƒWƒ^ƒ‹•ú‘—(D3 Cap)
Writing application                      : VirtualDubMod 1.5.10.1 (build 2439/release)
Writing library                          : VirtualDubMod build 2439/release
Comment                                  : CRC32F3FFC10EC

Video
ID                                       : 0
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L5.1
Format settings                          : CABAC / 2 Ref Frames
Format settings, CABAC                   : Yes
Format settings, Reference frames        : 2 frames
Codec ID                                 : H264
Duration                                 : 24 min 29 s
Bit rate                                 : 2 483 kb/s
Width                                    : 1 280 pixels
Height                                   : 720 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 23.976 (24000/1001) FPS
Original frame rate                      : 23.976 (23976/1000) FPS
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : Progressive
Bits/(Pixel*Frame)                       : 0.112
Stream size                              : 435 MiB (93%)
Writing library                          : x264 core 48 svn-537
Encoding settings                        : cabac=1 / ref=1 / deblock=0:0:0 / analyse=0x3:0x113 / me=hex / subme=6 / brdo=1 / mixed_ref=0 / me_range=16 / chroma_me=1 / trellis=1 / 8x8dct=1 / cqm=0 / chroma_qp_offset=0 / slices=1 / nr=0 / decimate=1 / bframes=2 / b_pyramid=0 / b_adapt=1 / b_bias=0 / direct=1 / wpredb=1 / bime=0 / keyint=200 / keyint_min=25 / scenecut=40 / rc=cqp / qp=21 / ip_ratio=1.40 / pb_ratio=1.30

Audio
ID                                       : 1
Format                                   : MPEG Audio
Format version                           : Version 1
Format profile                           : Layer 3
Codec ID                                 : 55
Codec ID/Hint                            : MP3
Duration                                 : 24 min 29 s
Bit rate mode                            : Constant
Bit rate                                 : 192 kb/s
Channel(s)                               : 2 channels
Sampling rate                            : 48.0 kHz
Frame rate                               : 41.667 FPS (1152 SPF)
Compression mode                         : Lossy
Stream size                              : 33.6 MiB (7%)
Alignment                                : Aligned on interleaves
Interleave, duration                     : 1001  ms (23.99 video frames)
Interleave, preload duration             : 504  ms
Writing library                          : LAME3.92 
Encoding settings                        : -m s -V 4 -q 2 -lowpass 18.7 -b 192

</p>
</details>
Issue happens across all my videos I try it on though, not an avi issue.
Ffmpeg and mkvtoolnix are in path.

**Comment by C1fer** [comment]
This should be fixed with the new media info parsing implemented in version 0.4.1.

**Comment by Asinin3** [comment]
Unfortunately, I still can't get this to work. I select the video input and target, then withing a second of the job starting it says "No completed jobs to merge!" and exits.

**Comment by C1fer** [comment]
Could you please check if there are any recent logs related to the process in the **Sushi Logs** folder?

**Comment by Asinin3** [comment]
@C1fer Where is the folder? I ran pip show sushi_batch, went to "C:\Users\Someone\AppData\Local\Programs\Python\Python313\Lib\site-packages\sushi_batch" and cant see it. There's nothing in the readme for where it is, and while the commands in the console have a clear logs option there's nothing there or in settings seemingly saying where the logs reside.

**Comment by C1fer** [comment]
Looks like I forgot to add the settings/log path in the readme.

This is the folder where the logs are stored:

macOS: `/Users/<your-user>/Documents/SushiBatchTool`
Windows: `C:\Users\<your-user>\Documents\SushiBatchTool`
Linux: `/home/<your-user>/Documents/SushiBatchTool`


Please attach the sushi log file if you manage to find it. This might give me some insight on what is causing this error.

**Comment by Asinin3** [comment]
Thanks, while you're fixing the readme, I noticed the video example has one with a .flac extension.

Anyway. I looked at the logs and always see the same issue in log "No subtitles streams found" in the SRC file.
Tried numerous files, doesnt matter if I go e.g BD to DVD or DVD to BD file order, or try numerous shows. Always same problem.
E.g:

[2026-04-21 - 21.45.57 - Akane-Iro Ni Somaru Saka.log](https://github.com/user-attachments/files/26934442/2026-04-21.-.21.45.57.-.Akane-Iro.Ni.Somaru.Saka.-.01.-.A.Madder.Red.First.Kiss.log)
[2025-12-23 - 21.07.03 - Hack_Roots.log](https://github.com/user-attachments/files/26934462/2025-12-23.-.21.07.03.-.Exiled-Destiny._Hack_Roots_Ep01_.5AB58043.log)

**Comment by C1fer** [comment]
Could you attach the output of this command using the source file defined in the Apr. 21st log?

``ffprobe -v quiet -print_format json=compact=1 -show_streams -show_entries "stream=index,codec_name,codec_type,sample_rate,channel_layout,bits_per_raw_sample,width,height:stream_tags=title,language:stream_disposition=default,forced" "/path/to/file"``

Replace "/path/to/file" with the src filepath

This is the ffmpeg command used in both sushi and sushi-batch to check for available audio and subtitle tracks in a video file.

**Comment by Asinin3** [comment]
Sure, this is same file as shown in SRC in first log above.
```
C:\Users\Someone>ffprobe -v quiet -print_format json=compact=1 -show_streams -show_entries "stream=index,codec_name,codec_type,sample_rate,channel_layout,bits_per_raw_sample,width,height:stream_tags=title,language:stream_disposition=default,forced" "Z:\anime\Akane-Iro Ni Somaru Saka - 01.mkv"
{
    "programs": [

    ],
    "stream_groups": [

    ],
    "streams": [
        { "index": 0, "codec_name": "h264", "codec_type": "video", "width": 1920, "height": 1080, "bits_per_raw_sample": "8",
            "disposition": { "default": 1, "forced": 0 },
            "tags": { "title": "ENCODED BY DARKDREAM" } },
        { "index": 1, "codec_name": "aac", "codec_type": "audio", "sample_rate": "48000", "channel_layout": "stereo",
            "disposition": { "default": 1, "forced": 0 },
            "tags": { "language": "jpn", "title": "Japanese" } },
        { "index": 2, "codec_name": "ass", "codec_type": "subtitle",
            "disposition": { "default": 1, "forced": 0 },
            "tags": { "language": "eng", "title": "English (Tsundere)" } },
        { "index": 3, "codec_name": "ttf", "codec_type": "attachment",
            "disposition": { "default": 0, "forced": 0 },
            "tags": {  } },
        { "index": 4, "codec_name": "ttf", "codec_type": "attachment",
            "disposition": { "default": 0, "forced": 0 },
            "tags": {  } },
        { "index": 5, "codec_name": "ttf", "codec_type": "attachment",
            "disposition": { "default": 0, "forced": 0 },
            "tags": {  } },
        { "index": 6, "codec_name": "ttf", "codec_type": "attachment",
            "disposition": { "default": 0, "forced": 0 },
            "tags": {  } },
        { "index": 7, "codec_name": "ttf", "codec_type": "attachment",
            "disposition": { "default": 0, "forced": 0 },
            "tags": {  } }
    ]
}
```
Index 2 above is the subtitle track, and it used "--src-script 2" in the command shown in log.

**Comment by C1fer** [comment]
Hi, 

Could you try again using v1.0.0? I made some fixes, so I think it should work now

**Comment by Asinin3** [comment]
I had the same issue with 1.0.0, log looks the same too. I did notice I dont have Aegisub-CLI, but that shouldn't matter, right?

**Comment by Asinin3** [comment]
@C1fer Same issue on 1.1.0 too :( exact same error in log on different files.

**Comment by C1fer** [comment]
Does the issue still occur when using Sushi directly? 

I'd suggest moving the source and target files to the root path of your C drive to test if this is an issue related to how Sushi handles file paths.
